name: test

on:
  workflow_dispatch:
  #push:
  #  branches:
 #     - master

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Setup Java Env
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: gradle

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "cachedir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ${{ steps.npm-cache-dir.outputs.cachedir }}
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    - name: Install dependencies
      shell: bash
      run: npm ci

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease \
            -PMYAPP_UPLOAD_STORE_FILE='release.keystore' \
            -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEY_ALIAS }}' \
            -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.STORE_PASSWORD }}' \
            -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
